### ISSUE TITLE
markdown-it-anchor permalinks get included in links titles

### ISSUE THREAD

**Issue by Princesseuh** [JordanShurmer/eleventy-plugin-nesting-toc#5]
When enabling markdown-it-anchor's permalinks (so permalinks are added next to titles), this plugin includes them in the toc (which is in most case, not desired)

It leads to results like this: 
![image](https://user-images.githubusercontent.com/3019731/113654777-9379dd80-9666-11eb-8750-4824760a71d9.png)

This didn't happen with `eleventy-plugin-toc`, the upstream version. In the upstream version, a simple hardcoded replace just removed the anchors, see [here](https://github.com/jdsteinbach/eleventy-plugin-toc/blob/master/src/SimplifyResults.js#L7). This work for my specific use case of having # as my permalink character however I'm sure a smarter solution could be found

A simple way to do it would be to replace `$el.text` by `$el.contents().first().text()`, however this would probably break when using the markdown-it-anchor setting to put the permalink before the text

**Comment by TaylanTatli** [comment]
I also came to report this. And removing just `#` won't work for me, because I use `🔗` as permalink symbol.
![2021 04 07-00 33 56](https://user-images.githubusercontent.com/754514/113781195-fb005d80-9738-11eb-8b43-db44c8bb881f.png)

**Comment by Princesseuh** [comment]
Created a PR for this #6

**Comment by JonUK** [comment]
I was just looking at this issue. Another way to resolve this (probably via an additional option) is to only use the heading text nodes in the immediate heading and ignore any other child elements. This would however mean that any child HTML elements (like `<strong>` or `<span>`) would be ignored.

```javascript
if (new option to strip child elements) {
  const textNodes = $el.contents().filter((_, item) => item.nodeType === 3);
  this.text = textNodes.text().trim();
} else {
  this.text = $el.text();
}
```

Given:
```
<h2 id="testHeading1">Heading Text <span>After</span></h2>
<h2 id="testHeading2"><span>Before</span> Heading Text</h2>
```

The heading text returned for both is `Heading Text`.

**Comment by Princesseuh** [comment]
Yes, I noticed this while making the PR (luckily I had a title with bold stuff in it or I would have missed it completely 😅)

I feel like it wouldn't create a pleasant experience for some normal markdown stuff to be ignored, we had that problem with a website using Gridsome and authors (who weren't into code) weren't pleased haha

This is why I opted for the solution I went with. I also wanted it to work in case text wasn't directly in the heading (I've seen this structure somewhere before)

**Comment by JonUK** [comment]
@Princesseuh Yes I like your approach as it's explicit about what elements are stripped out and is flexible where it uses CSS selectors.

**Comment by TaylanTatli** [comment]
Is npm package not updated?

**Comment by JordanShurmer** [comment]
v1.3.0 has been published to npm

/cc @TaylanTatli @Princesseuh @JonUK 

thanks a lot, all!

**Comment by Princesseuh** [comment]
Seems like the package.json hasn't been updated though 😅

**Comment by JordanShurmer** [comment]
@Princesseuh I see it there in npm. Version 1.3.0 has the code changes from #6 and the version bump in packages.json. Are you referring to something else not being updated in package.json?

**Comment by Princesseuh** [comment]
Oh, I might have just been checking the wrong branch then, sorry! Good work 👍
